#!/usr/bin/env node
'use strict'

const { INTERNAL_PUSH, checkReleases } = require('../scripts/release.cjs')

function run({ env = process.env, check = checkReleases } = {}) {
  return env[INTERNAL_PUSH] === '1' ? 0 : check({ env })
}

if (require.main === module) process.exitCode = run()

module.exports = { run }
